(motion_vectorization) root@30fb68955ee8:/workspace/MotionVectorization/RAFT# # تفعيل البيئة والتشغيل
conda activate motion_vectorization
./scripts/script.sh videos/test.txt
bash: ./scripts/script.sh: No such file or directory
(motion_vectorization) root@30fb68955ee8:/workspace/MotionVectorization/RAFT# cd /workspace/MotionVectorization
(motion_vectorization) root@30fb68955ee8:/workspace/MotionVectorization# export PYTHONPATH="${PYTHONPATH}:/workspace/MotionVectorization:/workspace/MotionVectorization/RAFT"
(motion_vectorization) root@30fb68955ee8:/workspace/MotionVectorization# touch RAFT/__init__.py
(motion_vectorization) root@30fb68955ee8:/workspace/MotionVectorization# python3 -c "import RAFT; print('RAFT import successful')"
RAFT import successful
(motion_vectorization) root@30fb68955ee8:/workspace/MotionVectorization# # التأكد من أننا في المجلد الصحيح والبيئة الصحيحة
conda activate motion_vectorization
pwd
ls scripts/

# تشغيل الاختبار
./scripts/script.sh videos/test.txt
/workspace/MotionVectorization
convert_to_svg.sh  extract_clusters.sh  extract_flow.sh  motion_file.sh  optim.sh  preprocess.sh  script.sh  track.sh
videos/test.txt
PREPROCESS
test1
RAFT
test1
/opt/miniconda3/envs/motion_vectorization/bin/python3: No module named RAFT.extract_flow
videos/test.txt
CLUSTER
test1
Traceback (most recent call last):
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/MotionVectorization/motion_vectorization/extract_clusters.py", line 11, in <module>
    from skimage.feature import canny
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/skimage/feature/__init__.py", line 4, in <module>
    from ._cascade import Cascade
  File "skimage/feature/_cascade.pyx", line 20, in init skimage.feature._cascade
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/skimage/transform/__init__.py", line 4, in <module>
    from .radon_transform import (radon, iradon, iradon_sart,
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/skimage/transform/radon_transform.py", line 5, in <module>
    from scipy.fft import fft, ifft, fftfreq, fftshift
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/scipy/fft/__init__.py", line 91, in <module>
    from ._helper import next_fast_len
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/scipy/fft/_helper.py", line 3, in <module>
    from ._pocketfft import helper as _helper
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/scipy/fft/_pocketfft/__init__.py", line 3, in <module>
    from .basic import *
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/scipy/fft/_pocketfft/basic.py", line 6, in <module>
    from . import pypocketfft as pfft
ImportError: /opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/../../libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/scipy/fft/_pocketfft/pypocketfft.cpython-38-x86_64-linux-gnu.so)
TRACK
Logging to motion_vectorization/logs/test1_track_32413.out
tee: motion_vectorization/logs/test1_track_32413.out: No such file or directory
Traceback (most recent call last):
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/MotionVectorization/motion_vectorization/extract_shapes.py", line 14, in <module>
    from skimage.transform import AffineTransform
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/skimage/transform/__init__.py", line 4, in <module>
    from .radon_transform import (radon, iradon, iradon_sart,
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/skimage/transform/radon_transform.py", line 5, in <module>
    from scipy.fft import fft, ifft, fftfreq, fftshift
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/scipy/fft/__init__.py", line 91, in <module>
    from ._helper import next_fast_len
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/scipy/fft/_helper.py", line 3, in <module>
    from ._pocketfft import helper as _helper
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/scipy/fft/_pocketfft/__init__.py", line 3, in <module>
    from .basic import *
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/scipy/fft/_pocketfft/basic.py", line 6, in <module>
    from . import pypocketfft as pfft
ImportError: /opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/../../libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/scipy/fft/_pocketfft/pypocketfft.cpython-38-x86_64-linux-gnu.so)
OPTIM
Logging to motion_vectorization/logs/test1_optim_7586.out
tee: motion_vectorization/logs/test1_optim_7586.out: No such file or directory
Traceback (most recent call last):
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/MotionVectorization/motion_vectorization/optimize_shapes.py", line 15, in <module>
    from skimage.transform import AffineTransform
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/skimage/transform/__init__.py", line 4, in <module>
    from .radon_transform import (radon, iradon, iradon_sart,
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/skimage/transform/radon_transform.py", line 5, in <module>
    from scipy.fft import fft, ifft, fftfreq, fftshift
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/scipy/fft/__init__.py", line 91, in <module>
    from ._helper import next_fast_len
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/scipy/fft/_helper.py", line 3, in <module>
    from ._pocketfft import helper as _helper
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/scipy/fft/_pocketfft/__init__.py", line 3, in <module>
    from .basic import *
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/scipy/fft/_pocketfft/basic.py", line 6, in <module>
    from . import pypocketfft as pfft
ImportError: /opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/../../libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/scipy/fft/_pocketfft/pypocketfft.cpython-38-x86_64-linux-gnu.so)
PROGRAM
Traceback (most recent call last):
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/MotionVectorization/motion_vectorization/create_motion_file.py", line 12, in <module>
    from .utils import get_numbers
  File "/workspace/MotionVectorization/motion_vectorization/utils.py", line 7, in <module>
    from skimage.segmentation import expand_labels
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/skimage/segmentation/__init__.py", line 3, in <module>
    from .active_contour_model import active_contour
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/skimage/segmentation/active_contour_model.py", line 6, in <module>
    from ..filters import sobel
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/skimage/_shared/lazy.py", line 64, in __getattr__
    submod = importlib.import_module(
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/skimage/filters/edges.py", line 17, in <module>
    from ..restoration.uft import laplacian
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/skimage/restoration/__init__.py", line 5, in <module>
    from .deconvolution import wiener, unsupervised_wiener, richardson_lucy
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/skimage/restoration/deconvolution.py", line 5, in <module>
    from scipy.signal import convolve
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/scipy/signal/__init__.py", line 309, in <module>
    from . import _sigtools, windows
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/scipy/signal/windows/__init__.py", line 41, in <module>
    from ._windows import *
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/scipy/signal/windows/_windows.py", line 7, in <module>
    from scipy import linalg, special, fft as sp_fft
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/scipy/fft/__init__.py", line 91, in <module>
    from ._helper import next_fast_len
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/scipy/fft/_helper.py", line 3, in <module>
    from ._pocketfft import helper as _helper
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/scipy/fft/_pocketfft/__init__.py", line 3, in <module>
    from .basic import *
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/scipy/fft/_pocketfft/basic.py", line 6, in <module>
    from . import pypocketfft as pfft
ImportError: /opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/../../libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /opt/miniconda3/envs/motion_vectorization/lib/python3.8/site-packages/scipy/fft/_pocketfft/pypocketfft.cpython-38-x86_64-linux-gnu.so)
(motion_vectorization) root@30fb68955ee8:/workspace/MotionVectorization# 